spring:
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: test-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      trusted-packages: com.technokratos.event
      type-mappings: starship:com.technokratos.event.StarshipEvent,string:java.lang.String
      enable-auto-commit: false

    producer:
      client-id: test-producer
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer