server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/agona_db
    username: Ekaterina
    password: eka_rina16
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  cloud:
    consul:
      discovery:
        hostname: host.docker.internal
        service-name: user-service
        instance-id: user-service-1
        health-check-path: /actuator/health
      host: host.docker.internal
      port: 8500

management:
  endpoints:
    web:
      exposure:
        include: health