spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      payment-failed-event-value-deserializer: org.apache.kafka.common.serialization.JsonDeserializer
      inventory-reserved-event-value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      inventory-failed-event-value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      trusted-packages: com.technokratos.event
      payment-failed-event-default-type: com.technokratos.event.PaymentFailedEvent
      inventory-reserved-event-default-type: com.technokratos.event.InventoryReservedEvent
      inventory-failed-event-default-type: com.technokratos.event.InventoryFailedEvent
      enable-auto-commit: true
    producer:
      client-id: test-producer
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      starship-value-serializer: org.springframework.kafka.support.serializer.JsonSerializer