stages:
  - build
  - deploy

build:
  stage: build
  script:
    - mvn clean install
  artifacts:
    paths:
      - target/Agona-05-1.0-SNAPSHOT.jar

deploy_main:
  stage: deploy
  only:
    - main

deploy_develop:
  stage: deploy
  only:
    - develop
