spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      order-created-event-value-deserializer: org.apache.kafka.common.serialization.JsonDeserializer
      payment-refund-event-value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      trusted-packages: com.technokratos.event
      order-created-event-default-type: com.technokratos.event.OrderCreatedEvent
      payment-refund-event-default-type: com.technokratos.event.PaymentRefundEvent
      enable-auto-commit: true
    producer:
      client-id: test-producer
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      payment-succeeded-value-serializer: org.apache.kafka.common.serialization.JsonSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
    prometheus:
      enabled: true